- name: Update System-Wide Profile for Kubernetes
  ansible.builtin.copy:
    dest: /etc/profile.d/kubernetes.sh
    content: |
      export KUBECONFIG=/etc/kubernetes/admin.conf
      export ANSIBLE_USER="root"

- name: Replace Docker daemon.json configuration
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Reload systemd configuration
  ansible.builtin.command:
    cmd: systemctl daemon-reload

- name: Restart Docker service
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Update Kubeadm Environment Variable
  ansible.builtin.command:
    cmd: sudo sed -i -e '/^\[Service\]/a Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"' /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

- name: Reload systemd configuration
  ansible.builtin.command:
    cmd: systemctl daemon-reload

- name: Restart kubelet service
  ansible.builtin.service:
    name: kubelet
    state: restarted

- name: Pull kubeadm container images
  ansible.builtin.command:
    cmd: sudo kubeadm config images pull

- name: Initialize Kubernetes control plane
  ansible.builtin.command:
    cmd: kubeadm init --control-plane-endpoint={{ansible_default_ipv4["address"]}} --pod-network-cidr={{ cni_network }} --upload-certs > /kubeadm_output
    creates: /kubeadm_output
  become: true
  changed_when: false 

- name: create .kube directoryi and copy kube config file
  shell: "{{ item }}"
  loop:
    - mkdir -p $HOME/.kube
    - cp /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config     

- name: Store Kubernetes initialization output to file
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /tmp/kubeadm_output
  become: false
  delegate_to: localhost

- name: Generate the Join Command
  ansible.builtin.shell: cat /tmp/kubeadm_output | tail -n 2 | sed ':a;N;$!ba;s/\\\n\s*/ /g' > /tmp/worker-join-command
  become: false
  delegate_to: localhost

- name: Set permissions for the Join Executable
  file:
    path: /tmp/worker-join-command
    state: file
    mode: '0755'
  become: false
  delegate_to: localhost


- name: Generate the Join Command
  ansible.builtin.shell: cat /tmp/kubeadm_output | sed -n '/kubeadm join/,/--control-plane/p'|head -3 > /tmp/master-join-command
  become: false
  delegate_to: localhost

- name: Set permissions for the Join Executable
  file:
    path: /tmp/master-join-command
    state: file
    mode: '0755'
  become: false
  delegate_to: localhost  


